development:
  adapter: postgresql
  database: env
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: env
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: env
  pool: 5
  timeout: 5000
